test

diff --git a/.github/workflows/contracts.yaml b/.github/workflows/contracts.yaml
--- a/.github/workflows/contracts.yaml
+++ b/.github/workflows/contracts.yaml
@@ -24,6 +24,10 @@ jobs:
       - uses: actions/checkout@v3
       - run: |
           DOJO_VERSION=$(grep 'dojo =' ./dojo-starter/.tool-versions | awk -F '"' '{print $2}')
+          if [ -z "$DOJO_VERSION" ]; then
+            echo "Error: Failed to extract Dojo version from ./dojo-starter/.tool-versions."
+            exit 1
+          fi
           echo "Extracted Dojo version: $DOJO_VERSION"
           echo "DOJO_VERSION=$DOJO_VERSION" >> $GITHUB_ENV
       - run: curl -L https://install.dojoengine.org | bash
